Use per-module Vulkan pipeline caches
kpet/clvk pull request #282
Opened 2020-12-22 22:39 UTC by jrprice

Compute the SHA-1 hash of the SPIR-V module and use that as a key for both in-memory and serialized caches of Vulkan pipelines caches.

Perform these cache lookups during program build. If there was a cache hit, we know that the SPIR-V has previously been validated, and so we can skip validation this time round. This significantly improves `clBuildProgram()` performance when creating programs from binaries.

I implemented the SHA-1 hashing from scratch, which avoids adding extra dependencies or the potential license complexities of incorporating third-party code into clvk directly. I've tested it against some of the test vectors available from NIST, but as I'm writing this I realize that I should probably add some unit tests for it here too.

The `cvk_device::get_pipeline_cache()` interface feels a little clunky; the `bool` result is used by the caller to avoid SPIR-V validation. The `bool` could be made an output parameter instead, but this didn't feel much better to me.

2020-12-23 21:47 UTC, jrprice commented
I've added a bunch of tests for the SHA-1 implementation now, taken from a set of tests provided by NIST. Good thing too - there was a few bugs in my implementation that are now fixed.

2021-01-08 11:53 UTC, kpet requested changes
I haven't reviewed the details of the SHA1 implementation (and probably will trust you and the testing). Overall looks good but now needs rebasing.

2021-01-08 13:03 UTC, jrprice commented
Addressed review comment and merged with master, PTAL.

2021-01-08 15:19 UTC, kpet approved these changes
LGTM!

2021-01-08 15:19 UTC, kpet commented on src/sha1.cpp
> +        data_i8 += 64;
I hadn't spotted the pointer arithmetic here. Probably still better to have the cast in the implementation.

2021-01-08 15:19 UTC, merged