fix vec3 arg size check in clSetKernelArg
kpet/clvk pull request #360
Opened 2022-03-07 16:11 UTC by rjodinchr

If a argument is a vec3, OpenCL requires the size passed to
clSetKernelArg to be 4 times the element size. Accept it even so clspv
arg size is 3 times the element size.

2022-03-09 13:45 UTC, rjodinchr commented
Compiling with `-cl-kernel-arg-info` enabled by default can be an issue.
Maybe just assuming that if size is exactly 4/3 of arg.size can be enough... as long as we take arg.size after that.
It would mean that we would accept wrong size in clSetKernel but it would not produced overflow or anything. Might be reasonable.

2022-03-13 11:34 UTC, kpet requested changes
I'm fine with this as a pragmatic (and hopefully temporary) solution though, as you say, requiring `-cl-kernel-arg-info` is not ideal. I looked at what clspv does layout-wise and currently it doesn't pack arguments so the space is wasted anyway there.

2022-03-13 11:34 UTC, kpet commented on src/kernel.hpp
> +                !(arg.info.type_name[arg.info.type_name.length() - 1] == '3' &&
I suggest you introduce `kernel_argument::is_vec3()` to help with readability (don't forget to assert the validity of `kernel_argument_info::extended_valid` there) and separation of concerns.

2022-03-14 20:54 UTC, kpet approved these changes
Thanks!

2022-03-14 20:54 UTC, merged