allow smaller batch and early flush
kpet/clvk pull request #421
Opened 2022-09-13 17:43 UTC by rjodinchr

add more values to configure clvk
add:
- max_first_batch_size
- max_group_size
- max_first_group_size
Those values have default value on a device level
They will be used by future commits

Keep track of the number of batch enqueued to be able to have a
smaller one when no batch has been enqueued to allow the GPU to start
computing earlier.
Keep track of the number of groups sent to the executor to be have to
have early flush of smaller groups to allow an early execution of
commands.

2022-09-14 18:00 UTC, kpet requested changes
I think those are valuable optimisations whose behaviour we will definitely want to configure differently depending on platforms, workloads, etc. I haven't looked too much at the implementation but I think it might make sense to rebase this PR on top of the config management one I've just opened (https://github.com/kpet/clvk/pull/423) so we don't introduce yet another way of reading values from environment variables. Scanning your code, it should be fairly straightforward to do. What do you think?

2022-09-15 07:53 UTC, rjodinchr commented
> I think those are valuable optimisations whose behaviour we will definitely want to configure differently depending on platforms, workloads, etc. I haven't looked too much at the implementation but I think it might make sense to rebase this PR on top of the config management one I've just opened (#423) so we don't introduce yet another way of reading values from environment variables. Scanning your code, it should be fairly straightforward to do. What do you think?

I agree, I will rebase on it.
The only not straightforward thing, is that I would like/need undefined values in the config.
Let's take `max_batch_size` as an example.
This value could come from:
- the default value for the platform (defined in `init_clvk_runtime_behaviors` in this PR)
- an override from the config file
- an override from the environment variable

So I would need to know whether the config file is overriding the default value for the platform or not.
Does it make sense?

2022-09-15 08:21 UTC, rjodinchr commented
I have rebased it on your branch.
And I have introduced an `UINT32_UNDEFINED`.

2022-09-15 08:46 UTC, kpet commented
>I have rebased it on your branch.

You will need to rebase on top of `main` now that the PR has gone in.

>And I have introduced an UINT32_UNDEFINED.

Hmm, I think my suggestion above is probably cleaner. I'll do a full review after you rebase it.

2022-09-15 16:07 UTC, rjodinchr commented
no regression on full cts with swiftshader and nvidia

2022-09-19 19:19 UTC, kpet requested changes
Thanks for the rebase! A few more changes and this will be ready to go.

2022-09-20 08:50 UTC, rjodinchr commented on src/api.cpp
> +        cvk_device->get_max_first_group_size());
Done

2022-09-20 08:50 UTC, rjodinchr commented on src/config.def
> +OPTION(uint32_t, max_first_group_size, UINT32_MAX)
I renamed them `max_cmd_*` to keep them not too long

2022-09-20 08:51 UTC, rjodinchr commented on src/device.hpp
> +
I did not do anything there.

2022-09-20 08:51 UTC, rjodinchr commented on src/queue.hpp
> +    cvk_command_queue* m_queue;
Done

2022-09-20 08:51 UTC, rjodinchr commented on src/queue.cpp
> +        batch_enqueued();
Yes, it feels better to have functions to manipulate it.

2022-09-20 08:51 UTC, rjodinchr commented on src/queue.hpp
> +    uint64_t m_nb_group_sent;
Done

2022-09-20 08:52 UTC, rjodinchr commented on src/queue.cpp
> +    m_queue->batch_completed();
Done

2022-09-20 08:52 UTC, rjodinchr commented on src/queue.cpp
> +        m_queue->group_completed();
Done

2022-09-20 20:13 UTC, kpet commented on src/config.def
> +OPTION(uint32_t, max_first_group_size, UINT32_MAX)
Good idea

2022-09-20 20:14 UTC, kpet approved these changes
Thanks!

2022-09-20 20:15 UTC, merged