Mark all args as set when cloning a kernel
kpet/clvk pull request #449
Opened 2022-11-04 16:27 UTC by callumfare

This fixes test_api/clone_kernel from the CTS

This contribution is being made by Codeplay on behalf of Samsung.

2022-11-04 16:57 UTC, kpet requested changes
I don't think that's correct: not all arguments are necessarily set at the time where cloning happens. Could you add a test, here or, even better, in the CTS, for the following scenario:
- Create kernel object for a given kernel in a program
- Set only part of its arguments
- Attempt to enqueue it, check that `CL_INVALID_KERNEL_ARGS` is returned
- Clone the kernel
- Attempt to enqueue the cloned kernel, check that `CL_INVALID_KERNEL_ARGS` is returned

As to how to implement it, I think we should probably move `cvk_kernel::m_args_set` into the `cvk_kernel_argument_values` object and let the latter's copy constructor handle the copy of the exact state.

2022-11-07 14:16 UTC, callumfare commented
Thanks for the review, that's what happens when I try to fix something last thing on a Friday! I've updated this PR to implement it as you suggested, and I've opened a new PR for the CTS to add an additional test case for `CL_INVALID_KERNEL_ARGS` - https://github.com/KhronosGroup/OpenCL-CTS/pull/1563

2022-11-09 20:44 UTC, kpet approved these changes

2022-11-09 20:44 UTC, kpet commented on src/kernel.cpp
> +                       [](bool b) { return b; });
You could delegate this to the arguments object to reduce what it exposes to just an `args_valid` function.

2022-11-09 20:45 UTC, kpet commented
Thanks! The change looks good. I've left a minor comment in case you're up for some more polishing but I'm fine merging the change as is and will do in a day or so if you don't push an update.

2022-11-10 18:21 UTC, kpet approved these changes
Thanks!

2022-11-10 18:21 UTC, kpet commented on src/kernel.cpp
> +bool cvk_kernel::args_valid() const { return m_argument_values->args_valid(); }
That could have been in the header but we've iterated enough on that change now :).

2022-11-10 18:21 UTC, merged