Add support for using buffer device addresses
kpet/clvk pull request #453
Opened 2022-11-10 15:15 UTC by callumfare

This enables use of physical addressing for global memory.

Requires the relevant clspv change: https://github.com/google/clspv/pull/954

I wasn't sure whether we want this to be enabled by default at this stage, so for now it requires `CLVK_PHYSICAL_ADDRESSING=1` to enable

This contribution is being made by Codeplay on behalf of Samsung.

2022-11-29 21:42 UTC, kpet commented
@callumfare I had spotted but I wanted to spend a bit more time reviewing and testing that one and ran out of time last weekend :). One thing I spotted on the first read though: I think I'd want us to have two config options, one for the number of address bits and another one for physical addressing. I expect physical/64 to become the default soon but it'd be good to retain the ability to quickly test other configurations.

2022-12-04 20:17 UTC, kpet requested changes
Thanks for this! Nothing too surprising overall. I've compared it against what I'd done as part of my SVM/USM prototype and it's missing a few things (i.e. usage flags) but nothing I can't land myself after I rebase (this will require changes to make usage flag determination dynamic which I've needed for 1D buffer image support as well).

I've run the CTS and it turned up a good number of regressions, we still have some work to do before we're able to make physical addressing the default. I've created https://github.com/kpet/clvk/issues/477 to track the transition.

More worryingly, this change doesn't pass clvk's `api_tests` when physical addressing is enabled and I think that ought to be fixed and regression testing put in place before we land this PR. I suggest copying the test step at https://github.com/kpet/clvk/blob/main/.github/workflows/presubmit.yml#L177 into a new `API tests (physical addressing)` step. It should just require a copy/paste and a couple additional environment variables (and fixing whatever prevents the `WithCommandQueue.PodUBO` test from passing of course :)).

2022-12-13 19:27 UTC, kpet commented
@callumfare Thanks! A few possible options:
1. Add support for Int64 to Swiftshader
2. Add support for `uint2` pointers to clspv (I remember @alan-baker was keen on seeing this done too)
3. We could land this PR with the new CI step disabled to get some forward progress (and add a task to https://github.com/kpet/clvk/issues/477). Not ideal but workable if sufficiently short-lived.

I have a strong preference for 1 or 2 but if you need 3, that's an acceptable compromise.

2022-12-14 17:00 UTC, callumfare commented
@kpet 

I think we'd prefer to go for option 3 as we ideally want all of our pending changes to be done in the next week or so - we (Codeplay) don't have plans to continue clvk/clspv contributions after this month. If it helps, I think we're happy to leave the option disabled by default, but in the short-term enable it on a per-device basis.

2022-12-18 13:07 UTC, kpet commented on src/kernel.hpp
> +                    mem_downcast->context()->device()->vulkan_device(), &info);
Yes, that makes sense.

2022-12-18 13:08 UTC, kpet approved these changes

2022-12-18 13:09 UTC, kpet commented
@callumfare Works for me. Noted, I'll try to get PRs in as soon as I can.

2022-12-18 13:09 UTC, merged