Implement clSetProgramSpecializationConstant
kpet/clvk pull request #478
Opened 2022-12-07 16:50 UTC by aarongreig

This contribution is being made by Codeplay on behalf of Samsung.

Depends on https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1758 (and a submodule bump which I will add here once that gets merged)

2022-12-29 14:56 UTC, aarongreig commented
My llvm-spirv patch merged but only after some breaking changes that'll necessitate a clspv llvm bump, I'm not going to have time to do the testing to make that change that so I'll wait until it happens and update here when it does.

2023-03-08 17:42 UTC, aarongreig commented
I think the remaining fail might be an issue with the CI, it looks like it's failing before the build gets to anything touched by my changes.

2023-03-11 10:51 UTC, kpet requested changes
Thanks! It's almost there, a few minor changes please (also merge conflicts need to be resolved).

2023-03-11 10:51 UTC, kpet commented on src/program.hpp
> +    user_spec_constant_data() : type(""), size(0), set(false) {}
Why is that constructor needed? Can we remove it?

2023-03-11 10:51 UTC, kpet commented on src/program.hpp
> +        }
We should probably have an else case to catch errors here or at least an assert.

2023-03-11 10:51 UTC, kpet commented on src/api.cpp
> +
A few more errors need to be handled here. Please handle them or add TODOs:

• CL_INVALID_OPERATION if no devices associated with program support intermediate language programs.
• CL_COMPILER_NOT_AVAILABLE if program is created with clCreateProgramWithIL and a compiler is not available, i.e. CL_DEVICE_COMPILER_AVAILABLE specified in the Device Queries table is set to CL_FALSE.
• CL_INVALID_VALUE if spec_value is NULL.

2023-03-11 10:51 UTC, kpet commented on src/program.cpp
> +        m_user_spec_constants[id] = user_spec_constant_data(type_string, size);
The lack of error handling is making me a bit nervous. Hopefully the translator does not change its output format too frequently and never produces output that would be invalid in a way that would trip this code over. Maybe a regex would be better? I think I'm fine with no change here.

2023-03-11 10:52 UTC, kpet commented
Also, I can confirm that the macOS CI error is spurious, I'll deal with this.

2023-03-31 00:06 UTC, kpet commented
@aarongreig Do you want to update the PR or should I take it over?

2023-04-03 20:28 UTC, kpet commented
@aarongreig It's gone in as https://github.com/kpet/clvk/pull/503. I think I've managed to retain your authorship. Thanks for the contribution!

2023-04-03 20:28 UTC, closed without merging

2023-04-04 08:48 UTC, aarongreig commented
thanks!