Draft: Physical module constants
kpet/clvk pull request #481
Opened 2022-12-09 14:41 UTC by callumfare

Add support for passing the module constants buffer as a device address push constant, so it can be used as a physical storage buffer.

This depends on this clspv change: https://github.com/google/clspv/pull/974
And the following update to the ClspvReflection instructions:
https://github.com/KhronosGroup/SPIRV-Headers/pull/308
https://github.com/KhronosGroup/SPIRV-Registry/pull/178

**This change is complete, but is marked as a draft as it depends on #453 which isn't merged yet. Only the top commit is relevant to this PR. I'm putting it up now to give context to help with the review of the ClspvReflection change.**

This contribution is being made by Codeplay on behalf of Samsung.

2023-02-26 14:31 UTC, kpet requested changes
@callumfare Are you able to update this PR or do you want me to take it over?

2023-02-26 14:31 UTC, kpet commented on src/program.cpp
> +            return true;
Maybe worth a comment explaining the early return.

2023-02-28 16:55 UTC, callumfare commented
> @callumfare Are you able to update this PR or do you want me to take it over?

Hi @kpet , we've reserved a little bit of time to help get the remaining PRs (this, printf, and spec constants) finished up and merged. I can address the review comments for this soon (this week) and do anything that needs done for the others. But if you want to get any of these in urgently feel free to take over any PRs before then.

2023-02-28 20:29 UTC, kpet commented
Great! Nothing urgent, I'll wait for your changes then. Thanks!

2023-03-06 21:05 UTC, kpet requested changes
Thanks for the changes! Just remove the dead code left behind and it's good to go.

2023-03-06 21:05 UTC, kpet commented on src/queue.cpp
> +        info.pNext = NULL;
```suggestion
```

This is now dead code.

2023-03-08 17:59 UTC, callumfare commented
> Thanks for the changes! Just remove the dead code left behind and it's good to go.

Thanks! That should it be it now

2023-03-08 22:03 UTC, kpet approved these changes
LGTM, thanks!

2023-03-08 22:03 UTC, merged