add test using perfetto in CI
kpet/clvk pull request #650
Opened 2024-01-13 09:15 UTC by rjodinchr

fix #442

2024-01-13 11:11 UTC, rjodinchr commented
I don't understand the error here. Feels like an issue with github trying to execute the `env` part of the `presubmit.yml`.
Can you reschedule it please?

2024-01-14 21:21 UTC, kpet commented on .github/workflows/presubmit.yml
> +          PERFETTO_DIR: '${{ github.workspace }}/external/perfetto'
```suggestion
          PERFETTO_DIR: ${{ github.workspace }}/external/perfetto
```

This might fix the issues you're seeing.

2024-01-15 19:20 UTC, rjodinchr commented
Only the macOS issue left!

At least the perfetto part looks ready for review

2024-01-16 10:03 UTC, kpet requested changes
Generally looks good, thanks! I think the expected output should be provided as a parameter to the checking script and the expectation file named after the corresponding test so it's easy to understand the relationship between the two and add further tests.

2024-01-16 16:41 UTC, kpet approved these changes
LGTM, thanks!

2024-01-16 18:05 UTC, merged