This change introduces using cl_arm_printf with callbacks for using printf inside the kernel
kpet/clvk pull request #668
Opened 2024-03-05 22:51 UTC by Rekt3421

This changes is a part of a series which will address #578 . This change addresses point 3 out of 4.

2024-03-05 22:59 UTC, Rekt3421 commented on tests/api/printf.cpp
> +#define RETURN_ON_FAILURE(err, ret)                                            \
This is similar to the main one. Was having some trouble using ASSERT_CL_SUCCESS in some cases so just copied and reused this.

2024-03-05 23:00 UTC, Rekt3421 commented
There is one slight issue though how do I verify the contents of the printf buffer? I could not access the string from within the callback ( I am assuming perhaps this is due to some synchronization issue?)

2024-03-06 07:04 UTC, rjodinchr requested changes
You should rely on the framework used by `api_tests`. Everything is in `testcl.hpp`.
It will allow to easily manage release/destruction as well as testing the error code (removing the need for `RETURN_ON_FAILURE` that you added)

You will need to add things there to create your context I believe.

In the end, we should not have any function starting with `cl` in `printf.cpp`.

2024-03-06 07:04 UTC, rjodinchr commented on tests/api/printf.cpp
> +}
This function feels unnecessary

2024-03-06 07:41 UTC, rjodinchr commented on tests/api/printf.cpp
> +        CL_CONTEXT_PLATFORM, (cl_context_properties)gPlatform, 0};
I understand that this is part of the sample example [here](https://registry.khronos.org/OpenCL/extensions/arm/cl_arm_printf.html), but I don't think it is needed.

2024-03-08 09:59 UTC, closed without merging